volumes:
  sockets:

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - sockets:/sockets:rw
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.19"
          memory: "20MB"

  api-1:
    hostname: api-1
    image: paulohrpinheiro/rinha-api-v:v13
    environment:
      - SOCKET_PATH=/sockets/api-1.sock
      - RESOURCES_DIR=/resources
    volumes:
      - sockets:/sockets:rw
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.405"
          memory: "165MB"

  api-2:
    hostname: api-2
    image: paulohrpinheiro/rinha-api-v:v13
    environment:
      - SOCKET_PATH=/sockets/api-2.sock
      - RESOURCES_DIR=/resources
    volumes:
      - sockets:/sockets:rw
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.405"
          memory: "165MB"

networks:
  rinha-net:
    driver: bridge
