volumes:
  sockets:

services:
  vproxy:
    image: paulohrpinheiro/rinha-api-vproxy:v05
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets:rw
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "10MB"
    environment:
      - BACKENDS=/sockets/api-1.sock,/sockets/api-2.sock

  api-1:
    hostname: api-1
    image: paulohrpinheiro/rinha-api-v:v05
    environment:
      - SOCKET_PATH=/sockets/api-1.sock
      - RESOURCES_DIR=/resources
    volumes:
      - sockets:/sockets:rw
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "170MB"

  api-2:
    hostname: api-2
    image: paulohrpinheiro/rinha-api-v:v05
    environment:
      - SOCKET_PATH=/sockets/api-2.sock
      - RESOURCES_DIR=/resources
    volumes:
      - sockets:/sockets:rw
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "170MB"

networks:
  rinha-net:
    driver: bridge